-- KisanSync — seed data matching lib/mockData.ts.
-- Run AFTER supabase/schema.sql. Idempotent (upserts); safe to re-run.
-- Delete `kisansync` demo rows and re-run for a full demo reset.

begin;

-- Demo farmer (id matches DEMO_FARMER.id / DEMO_FARMER_PROFILE).
insert into public.farmers (id, village)
values ('farmer-ramesh', 'Belvai, Moodbidri Taluk')
on conflict (id) do update set village = excluded.village;

-- Locations seed data (geocoded canonical locations).
insert into public.locations (id, name, normalized_name, district, state, latitude, longitude)
values
  ('loc-moodbidri', 'Moodbidri', 'moodbidri', 'Dakshina Kannada', 'Karnataka', 13.0697, 74.9983),
  ('loc-belvai', 'Belvai', 'belvai', 'Dakshina Kannada', 'Karnataka', 13.1114, 75.0022),
  ('loc-karkala', 'Karkala', 'karkala', 'Udupi', 'Karnataka', 13.2167, 74.9972),
  ('loc-mangaluru', 'Mangaluru', 'mangaluru', 'Dakshina Kannada', 'Karnataka', 12.9141, 74.8560),
  ('loc-udupi', 'Udupi', 'udupi', 'Udupi', 'Karnataka', 13.3409, 74.7421),
  ('loc-kasaragod', 'Kasaragod', 'kasaragod', 'Kasaragod', 'Kerala', 12.4996, 74.9869),
  ('loc-kozhikode', 'Kozhikode', 'kozhikode', 'Kozhikode', 'Kerala', 11.2588, 75.7804),
  ('loc-bengaluru', 'Bengaluru', 'bengaluru', 'Bengaluru Urban', 'Karnataka', 12.9716, 77.5946),
  ('loc-bantwal', 'Bantwal', 'bantwal', 'Dakshina Kannada', 'Karnataka', 12.8906, 75.0347),
  ('loc-puttur', 'Puttur', 'puttur', 'Dakshina Kannada', 'Karnataka', 12.7667, 75.2000),
  ('loc-sullia', 'Sullia', 'sullia', 'Dakshina Kannada', 'Karnataka', 12.5667, 75.3833),
  ('loc-kundapura', 'Kundapura', 'kundapura', 'Udupi', 'Karnataka', 13.6268, 74.6917),
  ('loc-manipal', 'Manipal', 'manipal', 'Udupi', 'Karnataka', 13.3525, 74.7865),
  ('loc-surathkal', 'Surathkal', 'surathkal', 'Dakshina Kannada', 'Karnataka', 13.0116, 74.7943),
  ('loc-mysuru', 'Mysuru', 'mysuru', 'Mysuru', 'Karnataka', 12.2958, 76.6394),
  ('loc-hassan', 'Hassan', 'hassan', 'Hassan', 'Karnataka', 13.0033, 76.1004),
  ('loc-shivamogga', 'Shivamogga', 'shivamogga', 'Shivamogga', 'Karnataka', 13.9299, 75.5681),
  ('loc-hyderabad', 'Hyderabad', 'hyderabad', 'Hyderabad', 'Telangana', 17.3850, 78.4867),
  ('loc-delhi', 'Delhi', 'delhi', 'New Delhi', 'Delhi', 28.6139, 77.2090),
  ('loc-mumbai', 'Mumbai', 'mumbai', 'Mumbai', 'Maharashtra', 19.0760, 72.8777),
  ('loc-chennai', 'Chennai', 'chennai', 'Chennai', 'Tamil Nadu', 13.0827, 80.2707),
  ('loc-kochi', 'Kochi', 'kochi', 'Ernakulam', 'Kerala', 9.9312, 76.2673)
on conflict (id) do update set
  name = excluded.name,
  normalized_name = excluded.normalized_name,
  district = excluded.district,
  state = excluded.state,
  latitude = excluded.latitude,
  longitude = excluded.longitude;

-- Auto-generated by scripts/import_centres.ts
-- Master statutory procurement centre dataset: e-NAM, Agmarknet, State APMC Boards
insert into public.centres (
  id, name, canonical_name, state, district, subdistrict, location,
  latitude, longitude, distance_km, source, external_id, centre_type, address,
  capacity_per_day, processing_rate_per_hour, queue_count, booked_today,
  eligible_crops, opens_at, closes_at, active
) values
  ('centre-moodbidri', 'Moodbidri APMC Sub-Yard', 'Agricultural Produce Market Committee Sub-Yard Moodbidri', 'Karnataka', 'Dakshina Kannada', 'Moodbidri', 'Moodbidri', 13.0697, 74.9983, 8, 'ksamb', 'ksamb-dk-001', 'sub_yard', 'APMC Sub-Yard, Main Road, Moodbidri, Dakshina Kannada, Karnataka 574227', 100, 6, 5, 28, array['Paddy / Rice', 'Maize', 'Coconut', 'Groundnut', 'Black Gram', 'Green Gram'], '08:00', '19:00', true),
  ('centre-karkala', 'Karkala APMC Yard & Co-op', 'APMC Market Yard Karkala', 'Karnataka', 'Udupi', 'Karkala', 'Karkala', 13.2167, 74.9972, 18, 'ksamb', 'ksamb-udp-002', 'apmc_mandi', 'APMC Yard, Bandimatha, Karkala, Udupi, Karnataka 574104', 60, 5, 4, 22, array['Paddy / Rice', 'Maize', 'Coconut', 'Arecanut', 'Black Gram', 'Green Gram'], '08:30', '18:00', true),
  ('centre-belvai', 'Belvai Primary Agri Co-op', 'Belvai Primary Agricultural Co-operative Society', 'Karnataka', 'Dakshina Kannada', 'Moodbidri', 'Belvai', 13.1114, 75.0022, 4, 'ksamb', 'pacs-dk-003', 'cooperative_society', 'PACS Centre, Belvai Junction, Moodbidri Taluk, Dakshina Kannada, Karnataka 574213', 40, 4, 4, 16, array['Paddy / Rice', 'Chilli', 'Tomato', 'Potato', 'Black Gram', 'Green Gram'], '09:00', '17:00', true),
  ('centre-mangaluru', 'Mangaluru APMC Main Yard (Baikampady)', 'APMC Main Market Yard Baikampady', 'Karnataka', 'Dakshina Kannada', 'Mangaluru', 'Mangaluru', 12.9431, 74.8197, 24, 'ksamb', 'ksamb-dk-004', 'apmc_mandi', 'APMC Yard, Baikampady Industrial Area, Mangaluru, Karnataka 575011', 120, 7, 11, 55, array['Paddy / Rice', 'Coconut', 'Arecanut', 'Chilli', 'Black Gram', 'Green Gram'], '07:30', '19:00', true),
  ('centre-udupi', 'Udupi APMC Yard (Adi-Udupi)', 'APMC Main Market Yard Adi-Udupi', 'Karnataka', 'Udupi', 'Udupi', 'Udupi', 13.3289, 74.7431, 32, 'ksamb', 'ksamb-udp-005', 'apmc_mandi', 'APMC Yard, Malpe Road, Adi-Udupi, Udupi, Karnataka 576103', 90, 6, 9, 42, array['Paddy / Rice', 'Coconut', 'Groundnut', 'Chilli', 'Black Gram', 'Green Gram'], '08:00', '18:30', true),
  ('centre-bantwal', 'Bantwal APMC Yard (B.C. Road)', 'APMC Market Yard B.C. Road Bantwal', 'Karnataka', 'Dakshina Kannada', 'Bantwal', 'Bantwal', 12.8797, 75.0289, 21, 'ksamb', 'ksamb-dk-006', 'apmc_mandi', 'APMC Yard, B.C. Road, Bantwal, Dakshina Kannada, Karnataka 574219', 75, 5.5, 7, 35, array['Paddy / Rice', 'Arecanut', 'Coconut', 'Black Gram'], '08:00', '18:00', true),
  ('centre-puttur', 'Puttur APMC Main Yard', 'APMC Main Market Yard Puttur', 'Karnataka', 'Dakshina Kannada', 'Puttur', 'Puttur', 12.7667, 75.2, 38, 'ksamb', 'ksamb-dk-007', 'apmc_mandi', 'APMC Yard, APMC Road, Puttur, Dakshina Kannada, Karnataka 574201', 80, 5, 8, 30, array['Arecanut', 'Paddy / Rice', 'Coconut', 'Black Gram'], '08:00', '18:00', true),
  ('centre-kundapura', 'Kundapura APMC Yard', 'APMC Market Yard Kundapura', 'Karnataka', 'Udupi', 'Kundapura', 'Kundapura', 13.6268, 74.6917, 65, 'ksamb', 'ksamb-udp-008', 'apmc_mandi', 'APMC Yard, Shastri Circle, Kundapura, Udupi, Karnataka 576201', 70, 5, 6, 28, array['Paddy / Rice', 'Groundnut', 'Coconut', 'Black Gram'], '08:30', '18:00', true),
  ('centre-bengaluru', 'Bengaluru APMC (Yeshwanthpur)', 'APMC Yeshwanthpur RMC Yard', 'Karnataka', 'Bengaluru Urban', 'Bengaluru North', 'Bengaluru', 13.0189, 77.5458, 280, 'enam', 'enam-ka-010', 'apmc_mandi', 'RMC Yard, Yeshwanthpur, Bengaluru, Karnataka 560022', 150, 8, 8, 40, array['Paddy / Rice', 'Maize', 'Tomato', 'Potato', 'Groundnut', 'Chilli', 'Black Gram', 'Green Gram'], '07:30', '19:30', true),
  ('centre-bengaluru-chamarajpet', 'Bengaluru APMC Sub-Yard (Binny Mill)', 'APMC Sub-Yard Binny Mill Chamarajpet', 'Karnataka', 'Bengaluru Urban', 'Bengaluru South', 'Bengaluru', 12.9625, 77.5681, 278, 'ksamb', 'ksamb-bng-012', 'sub_yard', 'Binny Mill Road, Cottonpet / Chamarajpet, Bengaluru, Karnataka 560053', 110, 7, 12, 48, array['Paddy / Rice', 'Maize', 'Groundnut', 'Black Gram', 'Green Gram', 'Chilli'], '08:00', '19:00', true),
  ('centre-bengaluru-dasanapura', 'Dasanapura APMC Sub-Yard', 'APMC Sub-Yard Dasanapura', 'Karnataka', 'Bengaluru Urban', 'Bengaluru North', 'Dasanapura', 13.0642, 77.4378, 295, 'ksamb', 'ksamb-bng-011', 'sub_yard', 'Tumkur Road, Dasanapura Hobli, Bengaluru North, Karnataka 562123', 90, 6, 5, 24, array['Tomato', 'Potato', 'Chilli', 'Paddy / Rice', 'Maize'], '08:00', '18:30', true),
  ('centre-bengaluru-hoskote', 'Hoskote APMC Yard', 'APMC Market Yard Hoskote', 'Karnataka', 'Bengaluru Rural', 'Hoskote', 'Hoskote', 13.0712, 77.7981, 305, 'enam', 'enam-ka-013', 'apmc_mandi', 'Old Madras Road, Hoskote, Bengaluru Rural, Karnataka 562114', 100, 6.5, 10, 52, array['Tomato', 'Potato', 'Maize', 'Paddy / Rice', 'Chilli', 'Groundnut'], '08:00', '18:00', true),
  ('centre-mysuru', 'Mysuru APMC Yard (Bandipalya)', 'APMC Main Market Yard Bandipalya', 'Karnataka', 'Mysuru', 'Mysuru', 'Mysuru', 12.2689, 76.6694, 210, 'enam', 'enam-ka-014', 'apmc_mandi', 'Bandipalya APMC Yard, Nanjangud Road, Mysuru, Karnataka 570025', 110, 7, 7, 38, array['Paddy / Rice', 'Maize', 'Groundnut', 'Tomato', 'Chilli', 'Black Gram'], '08:00', '19:00', true),
  ('centre-hassan', 'Hassan APMC Yard', 'APMC Main Market Yard Hassan', 'Karnataka', 'Hassan', 'Hassan', 'Hassan', 13.0125, 76.095, 135, 'enam', 'enam-ka-015', 'apmc_mandi', 'B.M. Road, Hassan, Karnataka 573201', 90, 6, 6, 31, array['Potato', 'Maize', 'Paddy / Rice', 'Chilli', 'Coconut'], '08:30', '18:30', true),
  ('centre-shivamogga', 'Shivamogga APMC Yard', 'APMC Main Market Yard Shivamogga', 'Karnataka', 'Shivamogga', 'Shivamogga', 'Shivamogga', 13.935, 75.58, 120, 'enam', 'enam-ka-016', 'apmc_mandi', 'Sagar Road, Shivamogga, Karnataka 577204', 85, 5.5, 8, 36, array['Arecanut', 'Paddy / Rice', 'Maize', 'Chilli', 'Groundnut'], '08:00', '18:00', true),
  ('centre-hubballi', 'Hubballi APMC Yard (Amargol)', 'APMC Main Market Yard Amargol', 'Karnataka', 'Dharwad', 'Hubballi', 'Hubballi', 15.3958, 75.105, 260, 'enam', 'enam-ka-017', 'apmc_mandi', 'Amargol APMC Yard, PB Road, Hubballi, Karnataka 580025', 130, 8, 15, 62, array['Chilli', 'Groundnut', 'Maize', 'Paddy / Rice', 'Black Gram', 'Green Gram'], '07:30', '19:30', true),
  ('centre-kozhikode-palayam', 'Palayam Wholesale Agri Market (Kozhikode)', 'Palayam Regulated Market Yard Kozhikode', 'Kerala', 'Kozhikode', 'Kozhikode', 'Kozhikode', 11.2483, 75.7845, 215, 'vfpck', 'vfpck-kzk-020', 'apmc_mandi', 'Palayam Market Road, Near Calicut Railway Station, Kozhikode, Kerala 673002', 90, 6, 5, 28, array['Paddy / Rice', 'Coconut', 'Tomato', 'Chilli', 'Black Gram', 'Green Gram'], '07:30', '18:30', true),
  ('centre-kozhikode-vengeri', 'Vengeri Wholesale Agri Market', 'Vengeri Urban Wholesale Agricultural Market', 'Kerala', 'Kozhikode', 'Kozhikode', 'Kozhikode', 11.3045, 75.7967, 210, 'vfpck', 'vfpck-kzk-021', 'apmc_mandi', 'Vengeri Market Complex, Balussery Road, Kozhikode, Kerala 673010', 80, 5.5, 9, 35, array['Coconut', 'Paddy / Rice', 'Tomato', 'Potato', 'Chilli', 'Black Gram', 'Green Gram'], '08:00', '18:00', true),
  ('centre-kozhikode-koyilandy', 'Koyilandy Regulated Market Yard', 'Regulated Market Yard Koyilandy', 'Kerala', 'Kozhikode', 'Koyilandy', 'Koyilandy', 11.4394, 75.6961, 195, 'vfpck', 'vfpck-kzk-022', 'collection_centre', 'National Highway 66, Koyilandy, Kozhikode, Kerala 673305', 55, 4.5, 4, 18, array['Coconut', 'Paddy / Rice', 'Black Gram', 'Green Gram'], '08:30', '17:30', true),
  ('centre-kozhikode-thamarassery', 'Thamarassery Agri Collection Hub', 'Primary Agricultural Collection Hub Thamarassery', 'Kerala', 'Kozhikode', 'Thamarassery', 'Thamarassery', 11.4172, 75.9333, 205, 'vfpck', 'vfpck-kzk-023', 'collection_centre', 'Wayanad Road, Thamarassery, Kozhikode, Kerala 673573', 60, 4.5, 6, 22, array['Arecanut', 'Coconut', 'Paddy / Rice', 'Black Gram'], '08:30', '17:30', true),
  ('centre-kochi', 'Kochi Krishi Bhavan & Procurement Hub', 'Krishi Bhavan Procurement Hub Ernakulam', 'Kerala', 'Ernakulam', 'Kanayannur', 'Kochi', 9.9816, 76.2999, 380, 'agmarknet', 'agri-kl-024', 'msp_procurement_hub', 'Civil Station, Kakkanad / Ernakulam Market, Kochi, Kerala 682030', 80, 6, 6, 25, array['Paddy / Rice', 'Coconut', 'Groundnut', 'Black Gram', 'Green Gram'], '08:00', '18:00', true),
  ('centre-kasaragod-kanhangad', 'Kanhangad Regulated Market Yard', 'Kanhangad Regulated Agricultural Market', 'Kerala', 'Kasaragod', 'Hosdurg', 'Kanhangad', 12.3089, 75.0911, 85, 'vfpck', 'vfpck-ksg-025', 'apmc_mandi', 'Main Road, Kanhangad, Kasaragod, Kerala 671315', 65, 5, 7, 29, array['Arecanut', 'Coconut', 'Paddy / Rice', 'Black Gram'], '08:30', '17:30', true),
  ('centre-palakkad-alathur', 'Alathur Regulated Paddy Market', 'Alathur Regulated Paddy Market Yard', 'Kerala', 'Palakkad', 'Alathur', 'Alathur', 10.645, 76.5417, 310, 'enam', 'enam-kl-026', 'msp_procurement_hub', 'Market Yard Road, Alathur, Palakkad, Kerala 678541', 95, 6.5, 8, 44, array['Paddy / Rice', 'Coconut', 'Groundnut', 'Black Gram', 'Green Gram'], '08:00', '18:00', true),
  ('centre-thrissur', 'Thrissur Sakthan Wholesale Market', 'Sakthan Thampuran Wholesale Agri Market Thrissur', 'Kerala', 'Thrissur', 'Thrissur', 'Thrissur', 10.5186, 76.2167, 330, 'vfpck', 'vfpck-tsr-027', 'apmc_mandi', 'Sakthan Thampuran Nagar, Thrissur, Kerala 680001', 100, 6.5, 11, 48, array['Paddy / Rice', 'Coconut', 'Chilli', 'Tomato', 'Potato'], '07:30', '18:30', true),
  ('centre-delhi-azadpur', 'Azadpur APMC Mandi', 'Agricultural Produce Marketing Committee Azadpur', 'Delhi', 'North Delhi', 'Model Town', 'Delhi', 28.7133, 77.1703, 1750, 'damb', 'damb-del-030', 'apmc_mandi', 'New Subzi Mandi, Azadpur, North Delhi, Delhi 110033', 200, 10, 16, 82, array['Tomato', 'Potato', 'Chilli', 'Paddy / Rice', 'Maize', 'Groundnut', 'Black Gram', 'Green Gram'], '06:00', '20:00', true),
  ('centre-delhi-narela', 'Narela APMC Grain Mandi', 'APMC Food Grains Market Yard Narela', 'Delhi', 'North Delhi', 'Narela', 'Narela', 28.8528, 77.0945, 1770, 'damb', 'damb-del-031', 'apmc_mandi', 'Anaj Mandi, Narela, North Delhi, Delhi 110040', 130, 8, 9, 45, array['Paddy / Rice', 'Maize', 'Black Gram', 'Green Gram', 'Groundnut'], '07:30', '19:00', true),
  ('centre-delhi-ghazipur', 'Ghazipur APMC Mandi', 'APMC Fruit and Vegetable Market Ghazipur', 'Delhi', 'East Delhi', 'Mayur Vihar', 'Delhi', 28.6256, 77.3275, 1740, 'damb', 'damb-del-032', 'apmc_mandi', 'Fruit & Vegetable Market, Ghazipur, East Delhi, Delhi 110096', 140, 8, 12, 60, array['Tomato', 'Potato', 'Chilli', 'Maize', 'Black Gram', 'Green Gram'], '06:30', '19:30', true),
  ('centre-delhi-najafgarh', 'Najafgarh APMC Mandi', 'APMC Grain Market Yard Najafgarh', 'Delhi', 'South West Delhi', 'Najafgarh', 'Najafgarh', 28.6128, 76.9856, 1735, 'damb', 'damb-del-033', 'apmc_mandi', 'Main Najafgarh Anaj Mandi, South West Delhi, Delhi 110043', 100, 7, 7, 35, array['Paddy / Rice', 'Maize', 'Groundnut', 'Black Gram', 'Green Gram'], '08:00', '18:30', true),
  ('centre-delhi-keshopur', 'Keshopur APMC Subzi Mandi', 'APMC Subzi Mandi Keshopur', 'Delhi', 'West Delhi', 'Patel Nagar', 'Delhi', 28.6433, 77.0864, 1745, 'damb', 'damb-del-034', 'apmc_mandi', 'Outer Ring Road, Vikaspuri / Keshopur, West Delhi, Delhi 110018', 110, 7, 14, 55, array['Tomato', 'Potato', 'Chilli', 'Green Gram', 'Black Gram'], '07:00', '19:00', true),
  ('centre-hyderabad-bowenpally', 'Bowenpally Agricultural Market Yard', 'Agricultural Market Committee Bowenpally', 'Telangana', 'Hyderabad', 'Secunderabad', 'Hyderabad', 17.4739, 78.4842, 620, 'enam', 'enam-tg-040', 'apmc_mandi', 'Bowenpally Market Yard, Secunderabad, Hyderabad, Telangana 500011', 140, 8, 11, 65, array['Tomato', 'Potato', 'Chilli', 'Paddy / Rice', 'Maize', 'Groundnut', 'Black Gram', 'Green Gram'], '07:00', '19:30', true),
  ('centre-hyderabad-malakpet', 'Malakpet Agricultural Market Yard', 'Agricultural Market Committee Malakpet', 'Telangana', 'Hyderabad', 'Malakpet', 'Hyderabad', 17.3756, 78.4989, 615, 'enam', 'enam-tg-041', 'apmc_mandi', 'Mahbub Mansion, Malakpet, Hyderabad, Telangana 500036', 110, 7, 8, 45, array['Paddy / Rice', 'Maize', 'Chilli', 'Groundnut', 'Black Gram', 'Green Gram'], '08:00', '19:00', true),
  ('centre-hyderabad-gaddiannaram', 'Gaddiannaram Fruit & Agri Market', 'Agricultural Market Committee Gaddiannaram', 'Telangana', 'Rangareddy', 'Saroornagar', 'Hyderabad', 17.3622, 78.5328, 618, 'enam', 'enam-tg-042', 'apmc_mandi', 'Kothapet / Gaddiannaram, Rangareddy, Telangana 500035', 120, 7.5, 10, 50, array['Tomato', 'Chilli', 'Potato', 'Maize', 'Paddy / Rice'], '07:30', '19:00', true),
  ('centre-hyderabad-gudimalkapur', 'Gudimalkapur Vegetable & Agri Market', 'Agricultural Market Yard Gudimalkapur', 'Telangana', 'Hyderabad', 'Asifnagar', 'Hyderabad', 17.3808, 78.4422, 610, 'enam', 'enam-tg-043', 'apmc_mandi', 'Mehdipatnam Road, Gudimalkapur, Hyderabad, Telangana 500028', 100, 6.5, 6, 38, array['Tomato', 'Chilli', 'Potato', 'Groundnut', 'Black Gram', 'Green Gram'], '07:30', '18:30', true),
  ('centre-warangal-enumamula', 'Enumamula Agricultural Market Yard', 'Agricultural Market Yard Enumamula Warangal', 'Telangana', 'Warangal', 'Warangal', 'Warangal', 17.9856, 79.62, 720, 'enam', 'enam-tg-044', 'apmc_mandi', 'Khammam Road, Enumamula, Warangal, Telangana 506005', 160, 9, 18, 80, array['Chilli', 'Paddy / Rice', 'Maize', 'Groundnut', 'Black Gram', 'Green Gram'], '07:00', '20:00', true),
  ('centre-mumbai-vashi', 'Navi Mumbai APMC (Vashi)', 'APMC Market Yard Vashi Navi Mumbai', 'Maharashtra', 'Thane', 'Navi Mumbai', 'Navi Mumbai', 19.0747, 73.0039, 750, 'msamb', 'msamb-mh-050', 'apmc_mandi', 'Sector 19, Vashi, Navi Mumbai, Maharashtra 400703', 180, 9, 14, 70, array['Paddy / Rice', 'Tomato', 'Potato', 'Chilli', 'Groundnut', 'Maize', 'Black Gram', 'Green Gram'], '06:30', '20:00', true),
  ('centre-mumbai-kalyan', 'Kalyan APMC Market Yard', 'APMC Market Yard Kalyan', 'Maharashtra', 'Thane', 'Kalyan', 'Kalyan', 19.2372, 73.1306, 770, 'msamb', 'msamb-mh-051', 'apmc_mandi', 'Bail Bazar, Kalyan West, Thane, Maharashtra 421301', 110, 7, 8, 42, array['Paddy / Rice', 'Tomato', 'Potato', 'Chilli', 'Black Gram'], '07:30', '19:00', true),
  ('centre-mumbai-vasai', 'Vasai APMC Sub-Yard', 'APMC Sub-Yard Vasai', 'Maharashtra', 'Palghar', 'Vasai', 'Vasai', 19.38, 72.83, 780, 'msamb', 'msamb-mh-052', 'sub_yard', 'Station Road, Vasai Road West, Palghar, Maharashtra 401202', 75, 5.5, 5, 26, array['Paddy / Rice', 'Tomato', 'Chilli', 'Black Gram'], '08:00', '18:30', true),
  ('centre-pune-gultekdi', 'Pune APMC (Gultekdi)', 'APMC Market Yard Gultekdi Pune', 'Maharashtra', 'Pune', 'Haveli', 'Pune', 18.4908, 73.8683, 630, 'enam', 'enam-mh-053', 'apmc_mandi', 'Market Yard, Gultekdi, Pune, Maharashtra 411037', 150, 8.5, 13, 65, array['Tomato', 'Potato', 'Chilli', 'Maize', 'Groundnut', 'Paddy / Rice', 'Black Gram', 'Green Gram'], '07:00', '19:30', true),
  ('centre-nashik', 'Nashik APMC (Panchavati)', 'APMC Market Yard Panchavati Nashik', 'Maharashtra', 'Nashik', 'Nashik', 'Nashik', 20.0167, 73.8, 820, 'enam', 'enam-mh-054', 'apmc_mandi', 'Panchavati, Nashik, Maharashtra 422003', 130, 7.5, 10, 55, array['Tomato', 'Potato', 'Chilli', 'Maize', 'Groundnut'], '07:30', '19:00', true),
  ('centre-chennai-koyambedu', 'Koyambedu Wholesale Market (KWMC)', 'Koyambedu Wholesale Market Complex Chennai', 'Tamil Nadu', 'Chennai', 'Aminjikarai', 'Chennai', 13.0694, 80.1947, 560, 'agmarknet', 'tn-apmc-060', 'apmc_mandi', 'KWMC Complex, Koyambedu, Chennai, Tamil Nadu 600107', 170, 9, 15, 75, array['Tomato', 'Potato', 'Chilli', 'Paddy / Rice', 'Coconut', 'Groundnut', 'Black Gram', 'Green Gram'], '06:00', '20:00', true),
  ('centre-madurai', 'Madurai Regulated Market (Paravai)', 'Regulated Market Yard Paravai Madurai', 'Tamil Nadu', 'Madurai', 'Madurai North', 'Madurai', 9.9536, 78.0811, 460, 'enam', 'enam-tn-061', 'apmc_mandi', 'Paravai Regulated Market, Dindigul Main Road, Madurai, Tamil Nadu 625402', 90, 6, 7, 34, array['Paddy / Rice', 'Chilli', 'Groundnut', 'Black Gram', 'Green Gram'], '08:00', '18:00', true),
  ('centre-coimbatore', 'Coimbatore Regulated Market (R.S. Puram)', 'Regulated Market Yard R.S. Puram Coimbatore', 'Tamil Nadu', 'Coimbatore', 'Coimbatore South', 'Coimbatore', 11.0089, 76.9525, 340, 'enam', 'enam-tn-062', 'apmc_mandi', 'Diwan Bahadur Road, R.S. Puram, Coimbatore, Tamil Nadu 641002', 100, 6.5, 8, 40, array['Tomato', 'Coconut', 'Maize', 'Groundnut', 'Paddy / Rice'], '08:00', '18:30', true),
  ('centre-guntur', 'Guntur Agricultural Market Yard (Mirchi Yard)', 'Agricultural Market Committee Guntur Mirchi Yard', 'Andhra Pradesh', 'Guntur', 'Guntur', 'Guntur', 16.2917, 80.445, 710, 'enam', 'enam-ap-070', 'apmc_mandi', 'Chilli Yard, Narakodur Road, Guntur, Andhra Pradesh 522004', 160, 9, 16, 78, array['Chilli', 'Paddy / Rice', 'Black Gram', 'Green Gram', 'Groundnut'], '07:00', '20:00', true),
  ('centre-vijayawada', 'Vijayawada APMC Yard (Gollapudi)', 'Agricultural Market Yard Gollapudi Vijayawada', 'Andhra Pradesh', 'Krishna', 'Vijayawada Rural', 'Vijayawada', 16.5417, 80.5917, 740, 'enam', 'enam-ap-071', 'apmc_mandi', 'Gollapudi Market Yard, NH 65, Vijayawada, Andhra Pradesh 521225', 110, 7, 9, 42, array['Paddy / Rice', 'Chilli', 'Maize', 'Black Gram', 'Green Gram'], '07:30', '19:00', true),
  ('centre-ahmedabad', 'Ahmedabad APMC (Jamalpur)', 'APMC Market Yard Jamalpur Ahmedabad', 'Gujarat', 'Ahmedabad', 'Ahmedabad City', 'Ahmedabad', 23.0122, 72.5856, 1200, 'enam', 'enam-gj-080', 'apmc_mandi', 'Jamalpur Gate, Ahmedabad, Gujarat 380022', 140, 8, 12, 58, array['Tomato', 'Potato', 'Chilli', 'Groundnut', 'Paddy / Rice', 'Maize'], '07:00', '19:30', true),
  ('centre-surat', 'Surat APMC (Sahara Darwaja)', 'APMC Market Yard Sahara Darwaja Surat', 'Gujarat', 'Surat', 'Surat City', 'Surat', 21.1989, 72.8456, 990, 'enam', 'enam-gj-081', 'apmc_mandi', 'Sahara Darwaja, Ring Road, Surat, Gujarat 395002', 130, 7.5, 11, 52, array['Paddy / Rice', 'Tomato', 'Potato', 'Chilli', 'Groundnut'], '07:30', '19:00', true),
  ('centre-khanna', 'Khanna Grain Market Yard', 'APMC Main Grain Market Yard Khanna', 'Punjab', 'Ludhiana', 'Khanna', 'Khanna', 30.7067, 76.22, 2020, 'enam', 'enam-pb-090', 'apmc_mandi', 'Grand Trunk Road, Khanna, Ludhiana, Punjab 141401', 220, 11, 17, 95, array['Paddy / Rice', 'Maize', 'Black Gram', 'Green Gram'], '07:00', '20:00', true),
  ('centre-ludhiana', 'Ludhiana APMC Yard (Gill Road)', 'APMC Market Yard Gill Road Ludhiana', 'Punjab', 'Ludhiana', 'Ludhiana', 'Ludhiana', 30.8856, 75.8567, 2040, 'enam', 'enam-pb-091', 'apmc_mandi', 'Gill Road, Ludhiana, Punjab 141003', 130, 8, 10, 48, array['Paddy / Rice', 'Maize', 'Potato', 'Black Gram'], '07:30', '19:00', true),
  ('centre-ghaziabad', 'Ghaziabad Mandi (Sahibabad)', 'Krishi Utpadan Mandi Samiti Sahibabad', 'Uttar Pradesh', 'Ghaziabad', 'Ghaziabad', 'Ghaziabad', 28.6711, 77.3489, 1740, 'enam', 'enam-up-100', 'apmc_mandi', 'Sahibabad Mandi, Mohan Nagar Road, Ghaziabad, Uttar Pradesh 201005', 140, 8, 13, 62, array['Tomato', 'Potato', 'Paddy / Rice', 'Maize', 'Chilli', 'Green Gram'], '07:00', '19:30', true),
  ('centre-varanasi', 'Varanasi Mandi (Pahara)', 'Krishi Utpadan Mandi Samiti Pahara Varanasi', 'Uttar Pradesh', 'Varanasi', 'Varanasi', 'Varanasi', 25.3217, 82.975, 1480, 'enam', 'enam-up-101', 'apmc_mandi', 'Pahara Mandi, GT Road, Varanasi, Uttar Pradesh 221002', 110, 7, 8, 40, array['Paddy / Rice', 'Tomato', 'Potato', 'Black Gram', 'Green Gram'], '07:30', '19:00', true)
on conflict (id) do update set
  name = excluded.name,
  canonical_name = excluded.canonical_name,
  state = excluded.state,
  district = excluded.district,
  subdistrict = excluded.subdistrict,
  location = excluded.location,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  distance_km = excluded.distance_km,
  source = excluded.source,
  external_id = excluded.external_id,
  centre_type = excluded.centre_type,
  address = excluded.address,
  capacity_per_day = excluded.capacity_per_day,
  processing_rate_per_hour = excluded.processing_rate_per_hour,
  queue_count = excluded.queue_count,
  booked_today = excluded.booked_today,
  eligible_crops = excluded.eligible_crops,
  opens_at = excluded.opens_at,
  closes_at = excluded.closes_at,
  active = excluded.active;

-- Seed appointments for the centre dashboard queue (ids match lib/mockData.ts).
-- Tokens KS-101..KS-107 (no KS-104 — that is the demo farmer's first booking).
insert into public.appointments (
  id, token_number, farmer_id, farmer_name, centre_id, centre_name,
  crop, quantity_quintals, village, arrival_window, status, stage_index,
  estimated_amount_inr, booked_at
) values
  ('apt-ks-101', 'KS-101', 'farmer-ks-101', 'Lakshmi Rai', 'centre-moodbidri', 'Moodbidri APMC',
   'Paddy / Rice', 12, 'Moodbidri Taluk', '10:00 AM – 10:20 AM', 'slot_booked', 0,
   12 * 2300, now() - interval '3 hours'),
  ('apt-ks-102', 'KS-102', 'farmer-ks-102', 'Suresh Shetty', 'centre-moodbidri', 'Moodbidri APMC',
   'Coconut', 8, 'Moodbidri Taluk', '10:00 AM – 10:20 AM', 'arrived', 1,
   8 * 1800, now() - interval '3 hours'),
  ('apt-ks-103', 'KS-103', 'farmer-ks-103', 'Ganesh Poojary', 'centre-moodbidri', 'Moodbidri APMC',
   'Paddy / Rice', 20, 'Moodbidri Taluk', '10:00 AM – 10:20 AM', 'weighed', 2,
   20 * 2300, now() - interval '3 hours'),
  ('apt-ks-105', 'KS-105', 'farmer-ks-105', 'Vasanth Alva', 'centre-karkala', 'Karkala Co-op',
   'Arecanut', 6, 'Moodbidri Taluk', '10:00 AM – 10:20 AM', 'slot_booked', 0,
   6 * 3200, now() - interval '3 hours'),
  ('apt-ks-106', 'KS-106', 'farmer-ks-106', 'Prakash Nayak', 'centre-karkala', 'Karkala Co-op',
   'Paddy / Rice', 15, 'Moodbidri Taluk', '10:00 AM – 10:20 AM', 'slot_booked', 0,
   15 * 2300, now() - interval '3 hours'),
  ('apt-ks-107', 'KS-107', 'farmer-ks-107', 'Ravi Shetty', 'centre-belvai', 'Belvai Agro Hub',
   'Chilli', 10, 'Moodbidri Taluk', '10:00 AM – 10:20 AM', 'slot_booked', 0,
   10 * 3500, now() - interval '3 hours')
on conflict (token_number) do update set
  farmer_name = excluded.farmer_name,
  status = excluded.status,
  stage_index = excluded.stage_index,
  estimated_amount_inr = excluded.estimated_amount_inr;

-- Initial status-history events for the seed appointments.
insert into public.procurement_status (appointment_id, status)
select id, status from public.appointments
where id like 'apt-ks-1%' and id not in (
  select appointment_id from public.procurement_status
);

commit;
