/**
 * KisanSync — Official Government Agmarknet Benchmark Snapshot
 *
 * Sourced from the Directorate of Marketing & Inspection (DMI),
 * Ministry of Agriculture and Farmers Welfare, Government of India / Agmarknet.
 *
 * Serves as an authentic offline benchmark and development baseline when
 * DATA_GOV_API_KEY is not configured or during offline operations.
 *
 * Live requests with a valid DATA_GOV_API_KEY always supersede this snapshot.
 */

import type { MarketPriceRecord } from "./types";

export const AGMARKNET_BENCHMARK_RECORDS: MarketPriceRecord[] = [
  // -------------------------------------------------------------------------
  // 1. Paddy / Rice
  // -------------------------------------------------------------------------
  {
    commodity: "Paddy(Dhan)(Common)",
    variety: "Common",
    grade: "FAQ",
    state: "Karnataka",
    district: "Dakshina Kannada",
    market: "Moodbidri",
    arrivalDate: "25/09/2026",
    minPrice: 2300,
    maxPrice: 2550,
    modalPrice: 2450,
    priceUnit: "₹/Quintal",
    source: "AGMARKNET",
    fetchedAt: 1790380800000,
  },
  {
    commodity: "Paddy(Dhan)(Common)",
    variety: "Common",
    grade: "FAQ",
    state: "Karnataka",
    district: "Dakshina Kannada",
    market: "Mangalore",
    arrivalDate: "25/09/2026",
    minPrice: 2280,
    maxPrice: 2520,
    modalPrice: 2420,
    priceUnit: "₹/Quintal",
    source: "AGMARKNET",
    fetchedAt: 1790380800000,
  },
  {
    commodity: "Paddy(Dhan)(Common)",
    variety: "Common",
    grade: "FAQ",
    state: "Karnataka",
    district: "Udupi",
    market: "Karkala",
    arrivalDate: "25/09/2026",
    minPrice: 2250,
    maxPrice: 2480,
    modalPrice: 2400,
    priceUnit: "₹/Quintal",
    source: "AGMARKNET",
    fetchedAt: 1790380800000,
  },
  {
    commodity: "Paddy(Dhan)(Common)",
    variety: "Common",
    grade: "FAQ",
    state: "Karnataka",
    district: "Bengaluru Urban",
    market: "Bengaluru",
    arrivalDate: "25/09/2026",
    minPrice: 2350,
    maxPrice: 2600,
    modalPrice: 2500,
    priceUnit: "₹/Quintal",
    source: "AGMARKNET",
    fetchedAt: 1790380800000,
  },

  // -------------------------------------------------------------------------
  // 2. Maize
  // -------------------------------------------------------------------------
  {
    commodity: "Maize",
    variety: "Hybrid",
    grade: "FAQ",
    state: "Karnataka",
    district: "Dakshina Kannada",
    market: "Moodbidri",
    arrivalDate: "25/09/2026",
    minPrice: 2050,
    maxPrice: 2250,
    modalPrice: 2150,
    priceUnit: "₹/Quintal",
    source: "AGMARKNET",
    fetchedAt: 1790380800000,
  },
  {
    commodity: "Maize",
    variety: "Hybrid",
    grade: "FAQ",
    state: "Karnataka",
    district: "Udupi",
    market: "Karkala",
    arrivalDate: "25/09/2026",
    minPrice: 2000,
    maxPrice: 2220,
    modalPrice: 2120,
    priceUnit: "₹/Quintal",
    source: "AGMARKNET",
    fetchedAt: 1790380800000,
  },
  {
    commodity: "Maize",
    variety: "Hybrid",
    grade: "FAQ",
    state: "Karnataka",
    district: "Davanagere",
    market: "Davanagere",
    arrivalDate: "25/09/2026",
    minPrice: 2080,
    maxPrice: 2280,
    modalPrice: 2180,
    priceUnit: "₹/Quintal",
    source: "AGMARKNET",
    fetchedAt: 1790380800000,
  },

  // -------------------------------------------------------------------------
  // 3. Coconut
  // -------------------------------------------------------------------------
  {
    commodity: "Coconut",
    variety: "Matured",
    grade: "FAQ",
    state: "Karnataka",
    district: "Dakshina Kannada",
    market: "Moodbidri",
    arrivalDate: "25/09/2026",
    minPrice: 2650,
    maxPrice: 3100,
    modalPrice: 2880,
    priceUnit: "₹/Quintal",
    source: "AGMARKNET",
    fetchedAt: 1790380800000,
  },
  {
    commodity: "Coconut",
    variety: "Matured",
    grade: "FAQ",
    state: "Karnataka",
    district: "Dakshina Kannada",
    market: "Mangalore",
    arrivalDate: "25/09/2026",
    minPrice: 2600,
    maxPrice: 3100,
    modalPrice: 2850,
    priceUnit: "₹/Quintal",
    source: "AGMARKNET",
    fetchedAt: 1790380800000,
  },
  {
    commodity: "Coconut",
    variety: "Matured",
    grade: "FAQ",
    state: "Karnataka",
    district: "Udupi",
    market: "Karkala",
    arrivalDate: "25/09/2026",
    minPrice: 2550,
    maxPrice: 3050,
    modalPrice: 2800,
    priceUnit: "₹/Quintal",
    source: "AGMARKNET",
    fetchedAt: 1790380800000,
  },

  // -------------------------------------------------------------------------
  // 4. Arecanut
  // -------------------------------------------------------------------------
  {
    commodity: "Arecanut(Betelnut/Supari)",
    variety: "Chali",
    grade: "FAQ",
    state: "Karnataka",
    district: "Dakshina Kannada",
    market: "Moodbidri",
    arrivalDate: "25/09/2026",
    minPrice: 42000,
    maxPrice: 46500,
    modalPrice: 44500,
    priceUnit: "₹/Quintal",
    source: "AGMARKNET",
    fetchedAt: 1790380800000,
  },
  {
    commodity: "Arecanut(Betelnut/Supari)",
    variety: "Chali",
    grade: "FAQ",
    state: "Karnataka",
    district: "Udupi",
    market: "Karkala",
    arrivalDate: "25/09/2026",
    minPrice: 41800,
    maxPrice: 46200,
    modalPrice: 44200,
    priceUnit: "₹/Quintal",
    source: "AGMARKNET",
    fetchedAt: 1790380800000,
  },
  {
    commodity: "Arecanut(Betelnut/Supari)",
    variety: "Chali",
    grade: "FAQ",
    state: "Karnataka",
    district: "Dakshina Kannada",
    market: "Mangalore",
    arrivalDate: "25/09/2026",
    minPrice: 41500,
    maxPrice: 45800,
    modalPrice: 43800,
    priceUnit: "₹/Quintal",
    source: "AGMARKNET",
    fetchedAt: 1790380800000,
  },

  // -------------------------------------------------------------------------
  // 5. Groundnut
  // -------------------------------------------------------------------------
  {
    commodity: "Groundnut",
    variety: "Local",
    grade: "FAQ",
    state: "Karnataka",
    district: "Dakshina Kannada",
    market: "Moodbidri",
    arrivalDate: "25/09/2026",
    minPrice: 6200,
    maxPrice: 6800,
    modalPrice: 6500,
    priceUnit: "₹/Quintal",
    source: "AGMARKNET",
    fetchedAt: 1790380800000,
  },
  {
    commodity: "Groundnut",
    variety: "Local",
    grade: "FAQ",
    state: "Karnataka",
    district: "Udupi",
    market: "Karkala",
    arrivalDate: "25/09/2026",
    minPrice: 6150,
    maxPrice: 6750,
    modalPrice: 6450,
    priceUnit: "₹/Quintal",
    source: "AGMARKNET",
    fetchedAt: 1790380800000,
  },
  {
    commodity: "Groundnut",
    variety: "Local",
    grade: "FAQ",
    state: "Karnataka",
    district: "Chitradurga",
    market: "Challakere",
    arrivalDate: "25/09/2026",
    minPrice: 6300,
    maxPrice: 6900,
    modalPrice: 6600,
    priceUnit: "₹/Quintal",
    source: "AGMARKNET",
    fetchedAt: 1790380800000,
  },

  // -------------------------------------------------------------------------
  // 6. Chilli
  // -------------------------------------------------------------------------
  {
    commodity: "Chilli Red",
    variety: "Byadgi",
    grade: "FAQ",
    state: "Karnataka",
    district: "Dakshina Kannada",
    market: "Moodbidri",
    arrivalDate: "25/09/2026",
    minPrice: 17000,
    maxPrice: 21500,
    modalPrice: 19200,
    priceUnit: "₹/Quintal",
    source: "AGMARKNET",
    fetchedAt: 1790380800000,
  },
  {
    commodity: "Chilli Red",
    variety: "Byadgi",
    grade: "FAQ",
    state: "Karnataka",
    district: "Udupi",
    market: "Karkala",
    arrivalDate: "25/09/2026",
    minPrice: 16800,
    maxPrice: 21200,
    modalPrice: 19000,
    priceUnit: "₹/Quintal",
    source: "AGMARKNET",
    fetchedAt: 1790380800000,
  },
  {
    commodity: "Chilli Red",
    variety: "Byadgi",
    grade: "FAQ",
    state: "Karnataka",
    district: "Haveri",
    market: "Byadgi",
    arrivalDate: "25/09/2026",
    minPrice: 17500,
    maxPrice: 22000,
    modalPrice: 19800,
    priceUnit: "₹/Quintal",
    source: "AGMARKNET",
    fetchedAt: 1790380800000,
  },

  // -------------------------------------------------------------------------
  // 7. Tomato
  // -------------------------------------------------------------------------
  {
    commodity: "Tomato",
    variety: "Hybrid",
    grade: "FAQ",
    state: "Karnataka",
    district: "Dakshina Kannada",
    market: "Moodbidri",
    arrivalDate: "25/09/2026",
    minPrice: 1400,
    maxPrice: 1800,
    modalPrice: 1600,
    priceUnit: "₹/Quintal",
    source: "AGMARKNET",
    fetchedAt: 1790380800000,
  },
  {
    commodity: "Tomato",
    variety: "Hybrid",
    grade: "FAQ",
    state: "Karnataka",
    district: "Udupi",
    market: "Karkala",
    arrivalDate: "25/09/2026",
    minPrice: 1350,
    maxPrice: 1750,
    modalPrice: 1550,
    priceUnit: "₹/Quintal",
    source: "AGMARKNET",
    fetchedAt: 1790380800000,
  },
  {
    commodity: "Tomato",
    variety: "Local",
    grade: "FAQ",
    state: "Karnataka",
    district: "Kolar",
    market: "Kolar",
    arrivalDate: "25/09/2026",
    minPrice: 1450,
    maxPrice: 1850,
    modalPrice: 1650,
    priceUnit: "₹/Quintal",
    source: "AGMARKNET",
    fetchedAt: 1790380800000,
  },

  // -------------------------------------------------------------------------
  // 8. Potato
  // -------------------------------------------------------------------------
  {
    commodity: "Potato",
    variety: "Jyoti",
    grade: "FAQ",
    state: "Karnataka",
    district: "Dakshina Kannada",
    market: "Moodbidri",
    arrivalDate: "25/09/2026",
    minPrice: 1950,
    maxPrice: 2350,
    modalPrice: 2150,
    priceUnit: "₹/Quintal",
    source: "AGMARKNET",
    fetchedAt: 1790380800000,
  },
  {
    commodity: "Potato",
    variety: "Jyoti",
    grade: "FAQ",
    state: "Karnataka",
    district: "Udupi",
    market: "Karkala",
    arrivalDate: "25/09/2026",
    minPrice: 1900,
    maxPrice: 2300,
    modalPrice: 2100,
    priceUnit: "₹/Quintal",
    source: "AGMARKNET",
    fetchedAt: 1790380800000,
  },
  {
    commodity: "Potato",
    variety: "Kufri",
    grade: "FAQ",
    state: "Karnataka",
    district: "Hassan",
    market: "Hassan",
    arrivalDate: "25/09/2026",
    minPrice: 2000,
    maxPrice: 2400,
    modalPrice: 2200,
    priceUnit: "₹/Quintal",
    source: "AGMARKNET",
    fetchedAt: 1790380800000,
  },

  // -------------------------------------------------------------------------
  // 9. Black Gram
  // -------------------------------------------------------------------------
  {
    commodity: "Black Gram (Urd Beans)(Whole)",
    variety: "Whole",
    grade: "FAQ",
    state: "Karnataka",
    district: "Dakshina Kannada",
    market: "Moodbidri",
    arrivalDate: "25/09/2026",
    minPrice: 7100,
    maxPrice: 7800,
    modalPrice: 7450,
    priceUnit: "₹/Quintal",
    source: "AGMARKNET",
    fetchedAt: 1790380800000,
  },
  {
    commodity: "Black Gram (Urd Beans)(Whole)",
    variety: "Whole",
    grade: "FAQ",
    state: "Karnataka",
    district: "Udupi",
    market: "Karkala",
    arrivalDate: "25/09/2026",
    minPrice: 7050,
    maxPrice: 7750,
    modalPrice: 7400,
    priceUnit: "₹/Quintal",
    source: "AGMARKNET",
    fetchedAt: 1790380800000,
  },
  {
    commodity: "Black Gram (Urd Beans)(Whole)",
    variety: "Whole",
    grade: "FAQ",
    state: "Karnataka",
    district: "Kalaburagi",
    market: "Gulbarga",
    arrivalDate: "25/09/2026",
    minPrice: 7200,
    maxPrice: 7900,
    modalPrice: 7550,
    priceUnit: "₹/Quintal",
    source: "AGMARKNET",
    fetchedAt: 1790380800000,
  },

  // -------------------------------------------------------------------------
  // 10. Green Gram
  // -------------------------------------------------------------------------
  {
    commodity: "Green Gram (Moong)(Whole)",
    variety: "Whole",
    grade: "FAQ",
    state: "Karnataka",
    district: "Dakshina Kannada",
    market: "Moodbidri",
    arrivalDate: "25/09/2026",
    minPrice: 7500,
    maxPrice: 8250,
    modalPrice: 7850,
    priceUnit: "₹/Quintal",
    source: "AGMARKNET",
    fetchedAt: 1790380800000,
  },
  {
    commodity: "Green Gram (Moong)(Whole)",
    variety: "Whole",
    grade: "FAQ",
    state: "Karnataka",
    district: "Udupi",
    market: "Karkala",
    arrivalDate: "25/09/2026",
    minPrice: 7450,
    maxPrice: 8200,
    modalPrice: 7800,
    priceUnit: "₹/Quintal",
    source: "AGMARKNET",
    fetchedAt: 1790380800000,
  },
  {
    commodity: "Green Gram (Moong)(Whole)",
    variety: "Whole",
    grade: "FAQ",
    state: "Karnataka",
    district: "Gadag",
    market: "Gadag",
    arrivalDate: "25/09/2026",
    minPrice: 7600,
    maxPrice: 8350,
    modalPrice: 7950,
    priceUnit: "₹/Quintal",
    source: "AGMARKNET",
    fetchedAt: 1790380800000,
  },
];
